### ISSUE TITLE
TypeError: Cannot set property 'columns' of undefined

### ISSUE THREAD

**Issue by Prahadeesh92** [handsontable/ngHandsontable#223]
Hello all, I have been using Handsontable (0.13.1) and ngHansontable (0.3.17), now I am planning to move to the Handsontable Pro Version(1.12.0) and ngHandsontable (013.0). I am trying to implement the Pro version and facing issues while doing it. 
Please have a look at the error that I am getting

**angular.js:10147 TypeError: Cannot set property 'columns' of undefined
    at http://localhost:9000/vendor/ng-handsontable/ngHandsontable.js:489:40
    at Object.forEach (http://localhost:9000/bower_components/angular/angular.js:325:18)
    at Object.compile (http://localhost:9000/vendor/ng-handsontable/ngHandsontable.js:486:17)
    at applyDirectivesToNode (http://localhost:9000/bower_components/angular/angular.js:6530:32)
    at compileNodes (http://localhost:9000/bower_components/angular/angular.js:6093:15)
    at compileNodes (http://localhost:9000/bower_components/angular/angular.js:6105:15)
    at compileNodes (http://localhost:9000/bower_components/angular/angular.js:6105:15)
    at compile (http://localhost:9000/bower_components/angular/angular.js:6026:15)
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:4076:20
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:6768:13) <hot-table hot-id="my-handsontable" ng-show="projectDrawingObj.hotTableData" settings="projectDrawingObj.hotTableSettings" cells="onCellHandler" columns="columnData" datarows="projectDrawingObj.hotTableData" colwidths="projectDrawingObj.columnWidths">**

Below are the versions that I am using.

ngHandsontable - 0.13.0 (latest version)
Handsontable Pro - 1.12.0
angular - 1.2.29

**Comment by AMBudnik** [comment]
Hi @Prahadeesh92 

PRO is not compatible with the ngHandsontable. You will only get CSS working like in this example http://jsbin.com/kexagaveho/1/edit?html,js,output

**Comment by Prahadeesh92** [comment]
The same code is working for angular 1.4.8 but causing issues with angular 1.2.29. Am I getting this error because of different versions of angularJS??

**Comment by AMBudnik** [comment]
PRO is compatible with Angular but not with the AngularJS version. If you can switch to Angular (2) here's a wrapper that supports the newest Hndsontable PRO version https://github.com/handsontable/angular-handsontable

**Comment by Prahadeesh92** [comment]
I'm sorry can you explain a bit more about it. Do you mean it won't support the particular version(1.2.29) of angularJS or it doesn't even support angularJS.

**Comment by AMBudnik** [comment]
The options on Handsontable PRO are not added to the AngularJS syntax so they won't work.

**Comment by stilltorik** [comment]
It seems that at least some Handsontable PRO options are now available. See the list here: http://handsontable.github.io/ngHandsontable/demo/index.html#/intro-simple-example
